# Generated by Django 3.2.7 on 2021-10-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=122)),
                ('decs', models.TextField(max_length=122)),
                ('date', models.DateField()),
            ],
        ),
    ]
