# Generated by Django 3.2.7 on 2021-10-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('decs', models.TextField(max_length=122)),
                ('img', models.FileField(upload_to='uploads/')),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('profile_image', models.FileField(upload_to='profile_images/')),
                ('status', models.BooleanField()),
            ],
        ),
    ]
