# Generated by Django 3.2.7 on 2021-10-03 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_table',
            name='name',
            field=models.CharField(default=' ', max_length=122),
        ),
    ]
