# Generated by Django 3.2.7 on 2021-10-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact_table_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('img', models.FileField(upload_to='uploads/')),
                ('price', models.FloatField()),
            ],
        ),
    ]
