# Generated by Django 3.2.7 on 2021-10-18 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20211013_0931'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registation_table',
        ),
    ]
