# Generated by Django 3.2.7 on 2021-12-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_delete_registation_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=122)),
                ('price', models.FloatField()),
                ('quantity', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
