# Generated by Django 3.2.7 on 2021-12-21 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20211221_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='product_price',
        ),
    ]
