# Generated by Django 3.2.7 on 2021-12-22 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_table',
            name='id',
        ),
        migrations.AddField(
            model_name='contact_table',
            name='order_id',
            field=models.IntegerField(primary_key=True, serialize=False),
            # field=models.IntegerField(default = ' ' ,primary_key=True, serialize=False)
        ),
    ]
