# Generated by Django 3.2.7 on 2021-12-22 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20211222_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_table',
            old_name='order_id',
            new_name='id',
        ),
    ]
