# Generated by Django 3.2.7 on 2021-12-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_contact_table_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_table',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
