# Generated by Django 3.2.7 on 2021-12-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_contact_table_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_table',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
