# Generated by Django 3.2.7 on 2021-12-26 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_contact_table_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
    ]
