# Generated by Django 3.2.7 on 2021-12-26 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_delete_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact_table',
        ),
    ]
