# Generated by Django 3.2.7 on 2021-12-26 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_contact_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=122)),
                ('product_price', models.CharField(max_length=122)),
                ('quantity', models.CharField(max_length=122)),
            ],
        ),
    ]
