# Generated by Django 3.2.7 on 2022-01-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.CharField(default=' ', max_length=122),
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.CharField(default=' ', max_length=122),
        ),
    ]
