# Generated by Django 3.2.7 on 2022-01-16 12:35

from django.db import migrations, models
from datetime import datetime 



class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_order_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            # field=models.DateField(default=' '),
            field=models.DateField(default=datetime.now),
        ),
    ]
