# Generated by Django 3.2.7 on 2022-01-16 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
    ]
